### ISSUE TITLE
Occasional segfault.

### ISSUE THREAD

**Issue by magnetophon** [mtytel/helm#37] opened 2015-11-21 10:44 UTC
Again, don't know how to reproduce (yet), but I'm getting occasional segfaults, where helm takes ardour 4.4 down with it.

I don't have a debug build  of ardour available, and from what I remember, that isn't easily doable in NixOS. I forgot the details, sorry.

What's the recommended way of tracking this down?

**Comment by mtytel** [comment] 2015-11-21 19:06
Damn, these are the worst. I thought I fixed all the crashes.
I don't have a great way to track this down right now. I'll need to put in some logs and save the backtrace in a file when it crashes.

Before I do that, do you remember what you were doing when it crashed? Did you have automation enabled? Did you have more than one instance of Helm? Any information like that would help.

**Comment by magnetophon** [comment] 2015-11-22 01:41
I had no (external) automation, and 4 lv2 instances running.
Sorry, I can't remember any other specifics.

**Comment by kpanic** [comment] 2016-01-17 17:03
I have a kind of reproducible segfault with renoise + helm vst, it brings down everything.
@mtytel if needed I can share the `xrns` in private so that you can try to reproduce. (it does not happen always)
I am running under debian.

Also I have another issue. When I open a new renoise song, helm is silent even if it's receiving notes. If I load it again with my saved instrument it works

**Comment by trebmuh** [comment] 2016-09-10 22:07
I just had a segfault as well.
I was just playing with the standalone version, launched from the CLI, using JACK and a MIDI keyboard. I was testing different presets and at one point, helm become silent. I closed it, I tried to relaunch it but I had the segfault. I started it again from another terminal, and it worked great. I closed it, and retried from the terminal I launched helm first (when it became silent) and it segfaulted.
(running debian jessie updated and helm 0.8.6 from GIT)
Hope that helps.

**Comment by mtytel** [comment] 2017-06-10 01:43
I've fixed a few couple segfaults/silences regarding initial values (crashed on startup, silence on startup, etc), step sequencer (crashed when modulating) and some other GUI and modulation problems.

Since this issue doesn't have a repro that narrows it down to any of these specifically. We can reopen or file news issues when the next version (0.9) is out.

**Closed by mtytel** 2017-06-10 01:43 UTC
