### ISSUE TITLE
Modulation is sometimes not saved in Ardour

### ISSUE THREAD

**Issue by magnetophon** [mtytel/helm#36] opened 2015-11-21 10:40 UTC
I don't have a reproducible recipe (yet), but I've noticed that sometimes after re-opening a .ardour file, the modulation destinations and amounts are not saved, so the patch comes up without modulation.

**Comment by mtytel** [comment] 2015-11-21 19:00
Ok, I'll have to try and reproduce this.
I know there's some strange things going on with polyphonic modulation of stutter and formant filter params right now, not sure if that's related.

**Comment by magnetophon** [comment] 2015-11-22 01:43
I'm sure I wasn't modulating those, as none of my patches even have them enabled.

**Comment by Fak3** [comment] 2015-11-26 14:43
I bumped into this issue with "fluffy landscape" preset, it is always reproducible for me:

* Start Ardour with new session
* Add MIDI Track with Helm as instrument
* Choose "fluffy landscape" preset from bank
* Restart Ardour, saving session
* Open saved session

All the connctions of mono-lfo 1 and 2 and poly-lfo are lost.
Moreover - I tried to recreate connections as they should be in the preset (i opened anoter Helm in parallel to see original preset connections), but the sound produced is not the same as in original "fluffy landscape" preset. As something besides the modulator connections is missing...
I restored:
* mono-lfo1 -> sub-amp
* mono-lfo1 -> filter envelope
* mono-lfo2 -> mix-trans-1
* poly-lfo -> mix-trans-2

**Comment by magnetophon** [comment] 2015-11-28 15:40
After making 2 partial songs with Helm, it seems this issue is always there.
I'm using Ardour 4.4 and Helm 0.5.0.

**Comment by mtytel** [comment] 2015-12-11 13:55
Update: It looks like Ardour is saving all parameter values and then restoring them instead of allowing the plugin to save the entire state to memory. Problem is modulation routings aren't saved as parameters..

**Comment by falkTX** [comment] 2015-12-31 15:16
This can be easily fixed by using JucePlugin_WantsLV2State=1 in the lv2 makefile, instead of the current JucePlugin_WantsLV2State=0.
Or just remove that line altogether since the default value in the latest juce-lv2 wrapper is automatically set to 1.

See https://github.com/DISTRHO/juce/blob/master/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp#L23

**Comment by mtytel** [comment] 2015-12-31 15:24
😭
Such an easy fix.. Thanks so much!

**Comment by mtytel** [comment] 2016-01-05 02:21
Fixed!

**Closed by mtytel** 2016-01-05 02:21 UTC

**Comment by magnetophon** [comment] 2016-01-05 13:01
@falkTX  & @mtytel 
Thanks!
