### ISSUE TITLE
Feature Request: MPE Implementation

### ISSUE THREAD

**Issue by Ekolide** [mtytel/helm#205] opened 2018-08-21 15:25 UTC
The MPE spec was adopted by the MIDI foundation a while back and it would be cool to see it implemented in Helm.

https://www.midi.org/articles/midi-polyphonic-expression-mpe

**Comment by wolftune** [comment] 2018-10-04 21:40
I support this, but it's a duplicate of one I already opened https://github.com/mtytel/helm/issues/158 so this should be closed.

**Comment by mtytel** [comment] 2018-10-04 21:52
I have a seaboard block coming in the mail so maybe soon :P

**Closed as completed by mtytel** 2018-10-04 21:52 UTC
