### ISSUE TITLE
Automation via Ardour unreliable

### ISSUE THREAD

**Issue by thorwil** [mtytel/helm#33] opened 2015-10-27 12:09 UTC
Automating parameters like arpeggio-frequency only works sometimes and is ignored most of the time.  Since automating other plugins works, I assume it's an issue with Helm.

 There's no obvious trigger, but it maybe have to do with initial playhead position and cycle-boundaries (rgareus's suggestion, I'm clueless in that regard).

I have a fairly minimal test session, but can't attach it here :/

**Comment by mtytel** [comment] 2015-10-31 03:21
This could be because there are actually two parameters that control the rate of the arp, delay, etc. There's arpfrequency and arptempo. When the sync drop down (the grey box with the little icon) is put into free running mode, it uses arpfrequency. If it's in tempo/triplet/dot mode, it will use arptempo.

Let me know if that's not the issue. I guess this can be confusing, though I'm not sure I'll change it to be one parameter.

**Comment by thorwil** [comment] 2015-11-03 12:11
Ah, OK. This is part of the issue. So I should use arptempo.

But after loading my test session, Helm initially did react to arpfrequency. Brought up the GUI, arp is in tempo mode. A click to select tempo again and Helm doesn't react to arpfrequency anymore. With my full session, it seemed like the relative playhead position might play a role. As might the GUI being active or not.

**Comment by mtytel** [comment] 2015-11-11 22:48
Hmm. I'm not sure exactly what you're saying.
When the icon on under arp frequency shows the clock/pie icon, Helm should react to the arp_frequency parameter automation. But the icon is the note(tempo) icon, then Helm will instead react to the apr_tempo parameter automation. 

If the icon said tempo but Helm was reacting to the arp_frequency automation, then that's a problem. But I can't reproduce that behavior.

**Comment by thorwil** [comment] 2015-11-12 10:50
Here's an Ardour test session:
https://www.dropbox.com/s/nqj2su7umc9jhig/helm_test.tar.bz2?dl=0
Hit L for loop play and listen how Helm follows automation. Then open Helm's GUI and note how it now ignores the automation. At least here, and I just switched from the PPA to building latest git myself.

**Comment by thorwil** [comment] 2015-11-12 12:53
chaot4 reproduced this on Arch, with helm installed via aur.

**Comment by mtytel** [comment] 2015-11-22 20:48
Ooooohhh. Interesting.
I wonder if opening the GUI sets all the frequencies back into tempo mode.

Thanks that Ardour session really helped me. I should have a fix soon.

**Comment by mtytel** [comment] 2015-12-13 19:55
Alright, I believe I fixed this. It was a rounding error for indexed values.
You'll probably have to set the arp into free running (Hertz) mode in your project and resave the entire thing to see the fix. 
This is fixed in the development branch. If you're still seeing this error after upgrading to 0.6.0, let me know.

**Closed by mtytel** 2015-12-13 19:55 UTC
