### ISSUE TITLE
Aftertouch responds to velocity instead

### ISSUE THREAD

**Issue by unfa** [mtytel/helm#77] opened 2016-05-04 12:13 UTC
I'm using Mac OS X 10.5.7 on a refurbished Mac Pro, Cubase 7.5 and Helm 0.6.0 downloaded from the official site.

I tested aftertouch capabilities of my keyboard and NI Massive reacts as expected, but Helm seems to only get the first aftertouch message that comes after note on, then all the rest is ignored. No motion with aftertouch.

Can anybody confirm this behavior?

**Comment by unfa** [comment] 2016-05-04 13:20
Update:

Aftertouch messages are ignored whatsoever. Aftertouch in Helm works the same way as Velocity modulation source. It reacts to note velocity, not aftertouch messages.

**Comment by unfa** [comment] 2016-05-11 09:24
Bump! Can anyone confirm this behavior?

**Comment by mtytel** [comment] 2016-05-29 17:17
Sorry about the delay. Been pretty busy with stuff.
Reproed it and am working on a fix!

**Comment by mtytel** [comment] 2016-05-29 23:12
Hmmmm on second look it looks like it's working in *some* DAWs.
Reaper works fine. Ableton is broke. This needs a little more time and won't make it into the coming version :/

**Comment by avish** [comment] 2016-08-01 12:32
+1, confirmed here too with Ableton, and kind of a bummer :(

**Comment by mtytel** [comment] 2017-05-08 17:54
After more research the problem seems to be in JUCE or in the DAWs since in the DAWs where aftertouch doesn't work I don't get any MIDI messages when changing pressure.

Going to close this and try and find the problem in JUCE or whatever DAW.

**Closed by mtytel** 2017-05-08 17:54 UTC

**Comment by Lomacar** [comment] 2020-01-03 20:05
Why is this closed? I still have this problem. I am testing on a Roli Seaboard Block and a Sensel Morph.

**Comment by MIKKAZX** [comment] 2021-03-05 07:20
Same here. I have a Yamaha KX-88 and using Ardour on Linux with one of those cheap and nasty usb to MIDI controllers. I would love this to be fixed please!
