### ISSUE TITLE
Notes restart when using computer keyboard to play

### ISSUE THREAD

**Issue by Davvos11** [mtytel/helm#168] opened 2017-10-19 20:14 UTC
When I am using the standalone version of Helm and I use the keys on my computer keyboard to play, the note starts over after a short while. However, if I just hit any other key (does not mather which one) it stops repeating and the note stays on like it's supposed to. I've worked around this by creating a script that spams the spacebar, but this is far from optimal.
I am using Arch Linux and the latest version of helm-git from the AUR.
[A video in which I show the bug](https://youtu.be/rfejveBoy8Y)

**Comment by Harald-Koschinski** [comment] 2017-10-24 18:11
I observed the same in "standalone Version" and inside my DAW (Renoise). Not only with helm but with every instrument. In my opinion it's not a bug. Just the "keyboard repaeater" of your OS / Desktop Environment.
This was one reason for my final decision to buy a small Midi-Keyboard.

**Comment by mtytel** [comment] 2017-11-06 00:31
Yeah I think this an OS specific thing. If not it's a JUCE related bug because I just get key press/release events from them. Closing.

**Closed by mtytel** 2017-11-06 00:31 UTC
